services:
  - type: web
    name: kpmg-community-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - src/**
      - public/**
      - package.json
      - vite.config.ts
      - tailwind.config.js
      - tsconfig.json
    envVars:
      - key: NODE_ENV
        value: production
