# .github/workflows/keepalive.yml
name: keep-alive
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -fsS https://kpmg-community-backend.onrender.com/healthz || true
          curl -fsS https://kpmg-community.onrender.com || true
          curl -fsS https://kpmg-community-admin.onrender.com || true
